POST http://localhost:8080/posts/
Content-Type: application/json
Accept: application/json

{
    "Message": "Testing api!!"
}

###

PUT http://localhost:8080/posts/7
Content-Type: application/json
Accept: application/json

{
    "Message": "Testing api!!"
}

###

GET http://localhost:8080/posts/
Content-Type: application/json
Accept: application/json

###

DELETE http://localhost:8080/posts/3
Content-Type: application/json
Accept: application/json