POST http://localhost:8080/api/labels/
Content-Type: application/json
Accept: application/json

{
    "text": "Testing api!!",
    "target": "Testing api!!"
}

###

PUT http://localhost:8080/api/posts/1
Content-Type: application/json
Accept: application/json

{
    "Message": "Testing api updates!!"
}

###

GET http://localhost:8080/api/posts/
Content-Type: application/json
Accept: application/json

###

DELETE http://localhost:8080/api/posts/3
Content-Type: application/json
Accept: application/json